application: dotacareer
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /api/players/.*
  script: api.players.app

- url: /api/teams/.*
  script: api.teams.app

- url: /api/matches/.*
  script: api.matches.app

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest